# Use official lightweight Python image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy requirements first
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the src folder only
COPY src/ /app/src/

# Expose Flask port
EXPOSE 4000

# Run the Flask app
CMD ["python", "src/app.py"]
